name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: self-hosted
    steps:

    - name: Create a file
      run: |
        echo 'hello' > sandeep_test
        cp sandeep_test sandeep_test2
        rm sandeep_test
