name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: self-hosted
    steps:

    - name: Install CRC
      run: |
        sudo dnf install git -y
        cd $HOME
        git clone https://github.com/openstack-k8s-operators/install_yamls.git
        cd install_yamls/devsetup/scripts/
        bash crc-setup.sh https://developers.redhat.com/content-gateway/rest/mirror/pub/openshift-v4/clients/crc/latest/crc-linux-amd64.tar.xz password $HOME/token.txt
        
    - name: Install operator
      run: |
        eval $(crc oc-env)
        oc login -u kubeadmin -p password https://api.crc.testing:6443
        cd $HOME/install_yamls
        make crc_storage
        make mariadb
        make keystone
        sleep 60 # wait 60 seconds so that operator install completes successfully, will replace with better check
        make mariadb_deploy
        sleep 60 # wait 60 seconds so that mariadb service install successfully, will replace with better checks
        make keystone_deploy
        sleep 90 # wait 120 seconds so that keystone service install successfully, will replace with better checks

    - name: Post check to confirm keystone service is working
      run: |
        sudo dnf install python3-openstackclient -y
        export OS_PROJECT_NAME=admin
        export OS_USERNAME=admin
        export OS_PASSWORD=12345678
        export OS_AUTH_URL=http://keystone-public-openstack.apps-crc.testing
        export OS_USER_DOMAIN_NAME=Default
        export OS_PROJECT_DOMAIN_NAME=Default
        openstack token issue
